/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package morganmuseumproject;

import java.awt.Image;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajivbasnet
 */



public class ResultsForm extends javax.swing.JFrame {

 public static int itemCode;
 public static String itemName;
 public static String itemDescription;
 public static String itemDirection;
 public static ImageIcon newImage;
    /**
     * Creates new form ResultsForm
     */
    public ResultsForm() {
        
        initComponents();
        
        labelItemCode.setText("Item Code: " + Integer.toString(itemCode));
        labelItemName.setText("Item Name: " + itemName);
        labelItemDirection.setText(itemDirection);
        labelItemDescription.setText("<html>" + itemDescription + "</html>");
        labelItemImage.setIcon(newImage);
        
    }
    
    public void getSearchAttributes (String searchValue, Boolean byItemName, Boolean byItemCode){
        
        String qry ="";
        
        
        try {
           Class.forName("com.mysql.jdbc.Driver");  
           String url = new String();
           String user = new String();
           String password = new String();
           url = "jdbc:mysql://localhost:3306/morgan_museum_items";
           user = "root";
           password = "password";
           
           DriverManager.registerDriver(new com.mysql.jdbc.Driver());
           Connection conn = DriverManager.getConnection(url,user,password);
           Statement stment = conn.createStatement();
           
           if (byItemName == true) {
               qry = "SELECT * FROM item_info WHERE item_name='" + searchValue +"'"; 
           } 
           else if (byItemCode == true) {
               qry = "SELECT * FROM item_info WHERE item_code='" + searchValue +"'";
           }
           
           ResultSet rs = stment.executeQuery(qry);

                if(rs.next())
                {
                  do{

                        itemCode = rs.getInt("item_code");
                        itemName = rs.getString("item_name");
                        itemDescription = rs.getString("item_description");
                        itemDirection = rs.getString("item_direction");
                        
                        
                        byte[] img = rs.getBytes("item_image");
                        ImageIcon image = new ImageIcon(img);
                        Image im = image.getImage();
                        Image myImg = im.getScaledInstance(labelItemImage.getWidth(), labelItemImage.getHeight(), Image.SCALE_SMOOTH);
                        newImage = new ImageIcon(myImg);
                
                        
                    }
                    while(rs.next());
                }
                else
                {
                    showMessageDialog(null, "Sorry! The item was not found. PLEASE GO BACK and TRY AGAIN.", "ERROR",ERROR_MESSAGE);
                    itemCode = 0;
                    itemName = "N/A";
                    itemDescription = "N/A";
                    itemDirection = "N/A";
                    newImage = new ImageIcon();
                }
                conn.close();
        } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Database Connection Failed" +e);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeading = new javax.swing.JPanel();
        labelWelcome = new javax.swing.JLabel();
        labelMorgan = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        labelDescription = new javax.swing.JLabel();
        labelItem = new javax.swing.JLabel();
        labelDirections = new javax.swing.JLabel();
        separatorItem = new javax.swing.JSeparator();
        separatorDescription = new javax.swing.JSeparator();
        separatorDirections = new javax.swing.JSeparator();
        labelItemCode = new javax.swing.JLabel();
        labelItemName = new javax.swing.JLabel();
        labelItemDirection = new javax.swing.JLabel();
        labelItemImage = new javax.swing.JLabel();
        labelItemDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeading.setBackground(new java.awt.Color(165, 75, 75));

        labelWelcome.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome.setText("WELCOME TO");

        labelMorgan.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        labelMorgan.setText("Morgan Library and Museum");

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(161, 55, 55));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeadingLayout = new javax.swing.GroupLayout(panelHeading);
        panelHeading.setLayout(panelHeadingLayout);
        panelHeadingLayout.setHorizontalGroup(
            panelHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGroup(panelHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeadingLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(labelMorgan)
                        .addGap(130, 130, 130))
                    .addGroup(panelHeadingLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelHeadingLayout.setVerticalGroup(
            panelHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadingLayout.createSequentialGroup()
                .addGroup(panelHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeadingLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMorgan))
                    .addGroup(panelHeadingLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBack)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelBody.setBackground(new java.awt.Color(57, 43, 43));

        searchLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchLabel.setText("Search Result");

        labelDescription.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelDescription.setForeground(new java.awt.Color(255, 255, 255));
        labelDescription.setText("Description");

        labelItem.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelItem.setForeground(new java.awt.Color(255, 255, 255));
        labelItem.setText("Item");

        labelDirections.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelDirections.setForeground(new java.awt.Color(255, 255, 255));
        labelDirections.setText("Directions");

        labelItemCode.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelItemCode.setForeground(new java.awt.Color(255, 255, 255));
        labelItemCode.setText("Item Code: ");

        labelItemName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelItemName.setForeground(new java.awt.Color(255, 255, 255));
        labelItemName.setText("Item Name: ");

        labelItemDirection.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelItemDirection.setForeground(new java.awt.Color(255, 255, 255));
        labelItemDirection.setText("Item Direction: ");

        labelItemImage.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelItemImage.setForeground(new java.awt.Color(255, 255, 255));
        labelItemImage.setText("Image");
        labelItemImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelItemDescription.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelItemDescription.setForeground(new java.awt.Color(255, 255, 255));
        labelItemDescription.setText("Description");
        labelItemDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(searchLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBodyLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelItem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separatorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separatorDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separatorDirections, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDirections, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelItemDirection, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDescription)
                            .addComponent(labelItem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separatorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(separatorDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addComponent(labelItemCode)
                        .addGap(12, 12, 12)
                        .addComponent(labelItemName)
                        .addGap(24, 24, 24)
                        .addComponent(labelItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addComponent(labelItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDirections)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separatorDirections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelItemDirection)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SearchForm().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelDirections;
    private javax.swing.JLabel labelItem;
    private javax.swing.JLabel labelItemCode;
    private javax.swing.JLabel labelItemDescription;
    private javax.swing.JLabel labelItemDirection;
    private javax.swing.JLabel labelItemImage;
    private javax.swing.JLabel labelItemName;
    private javax.swing.JLabel labelMorgan;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeading;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JSeparator separatorDescription;
    private javax.swing.JSeparator separatorDirections;
    private javax.swing.JSeparator separatorItem;
    // End of variables declaration//GEN-END:variables
}
