/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package morganmuseumproject;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author rajivbasnet
 */
public class SearchForm extends javax.swing.JFrame {

    /**
     * Creates new form SearchForm
     */
    public SearchForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeading = new javax.swing.JPanel();
        labelWelcome = new javax.swing.JLabel();
        labelMorgan = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchItemTxtField = new javax.swing.JTextField();
        separatorSearch = new javax.swing.JSeparator();
        searchByItemCodeRadio = new javax.swing.JRadioButton();
        searchByItemNameRadio = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(57, 43, 43));
        setMinimumSize(new java.awt.Dimension(581, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeading.setBackground(new java.awt.Color(165, 75, 75));

        labelWelcome.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome.setText("WELCOME TO");

        labelMorgan.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        labelMorgan.setText("Morgan Library and Museum");

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(161, 55, 55));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeadingLayout = new javax.swing.GroupLayout(panelHeading);
        panelHeading.setLayout(panelHeadingLayout);
        panelHeadingLayout.setHorizontalGroup(
            panelHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadingLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(labelMorgan)
                .addGap(130, 130, 130))
        );
        panelHeadingLayout.setVerticalGroup(
            panelHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWelcome)
                .addGroup(panelHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeadingLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelMorgan))
                    .addGroup(panelHeadingLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnBack)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(panelHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 80));

        panelBody.setBackground(new java.awt.Color(57, 43, 43));

        searchLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchLabel.setText("Search Items");

        searchItemTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemTxtFieldActionPerformed(evt);
            }
        });

        searchByItemCodeRadio.setBackground(new java.awt.Color(35, 45, 45));
        searchByItemCodeRadio.setForeground(new java.awt.Color(255, 255, 255));
        searchByItemCodeRadio.setText("Search By Item Code");
        searchByItemCodeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByItemCodeRadioActionPerformed(evt);
            }
        });

        searchByItemNameRadio.setBackground(new java.awt.Color(35, 45, 45));
        searchByItemNameRadio.setForeground(new java.awt.Color(255, 255, 255));
        searchByItemNameRadio.setText("Search By Item Name");
        searchByItemNameRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByItemNameRadioActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(161, 55, 55));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(161, 55, 55));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBodyLayout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(searchByItemNameRadio))
                            .addGap(18, 18, 18)
                            .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(searchByItemCodeRadio)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBodyLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelBodyLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(separatorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(searchItemTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelBodyLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(searchLabel)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(searchItemTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchByItemNameRadio)
                    .addComponent(searchByItemCodeRadio))
                .addGap(37, 37, 37)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(panelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 580, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchItemTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchItemTxtFieldActionPerformed

    private void searchByItemCodeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByItemCodeRadioActionPerformed
        // TODO add your handling code here:
        searchByItemNameRadio.setSelected(false);
    }//GEN-LAST:event_searchByItemCodeRadioActionPerformed

    private void searchByItemNameRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByItemNameRadioActionPerformed
        // TODO add your handling code here:
        searchByItemCodeRadio.setSelected(false);
    }//GEN-LAST:event_searchByItemNameRadioActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        try{
            searchItemTxtField.setText("");
            searchByItemNameRadio.setSelected(false);
            searchByItemCodeRadio.setSelected(false);
            
        }
        catch (Exception e){
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchValue = searchItemTxtField.getText();
        Boolean byItemName = searchByItemNameRadio.isSelected();
        Boolean byItemCode = searchByItemCodeRadio.isSelected();

        if (searchValue.equals("") || (byItemName == false && byItemCode == false)){
            showMessageDialog(null, "Error! One or more search attribute is empty!", "ERROR",ERROR_MESSAGE);
        }
        else {
            ResultsForm toPass = new ResultsForm();
            toPass.getSearchAttributes(searchValue, byItemName, byItemCode);
            this.setVisible(false);
            new ResultsForm().setVisible(true);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HomePageForm().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel labelMorgan;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeading;
    private javax.swing.JRadioButton searchByItemCodeRadio;
    private javax.swing.JRadioButton searchByItemNameRadio;
    private javax.swing.JTextField searchItemTxtField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JSeparator separatorSearch;
    // End of variables declaration//GEN-END:variables
}
